<?php
/* Copyright (C) 2001-2005 Rodolphe Quiedeville <rodolphe@quiedeville.org>
 * Copyright (C) 2004-2015 Laurent Destailleur  <eldy@users.sourceforge.net>
 * Copyright (C) 2005-2012 Regis Houssin        <regis.houssin@inodbox.com>
 * Copyright (C) 2015      Jean-François Ferry	<jfefe@aternatik.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 *	\file       gpeccustom/gpeccustomindex.php
 *	\ingroup    gpeccustom
 *	\brief      Home page of gpeccustom top menu
 */

// Load Dolibarr environment
$res = 0;
// Try main.inc.php into web root known defined into CONTEXT_DOCUMENT_ROOT (not always defined)
if (!$res && !empty($_SERVER["CONTEXT_DOCUMENT_ROOT"])) {
	$res = @include $_SERVER["CONTEXT_DOCUMENT_ROOT"]."/main.inc.php";
}
// Try main.inc.php into web root detected using web root calculated from SCRIPT_FILENAME
$tmp = empty($_SERVER['SCRIPT_FILENAME']) ? '' : $_SERVER['SCRIPT_FILENAME']; $tmp2 = realpath(__FILE__); $i = strlen($tmp) - 1; $j = strlen($tmp2) - 1;
while ($i > 0 && $j > 0 && isset($tmp[$i]) && isset($tmp2[$j]) && $tmp[$i] == $tmp2[$j]) {
	$i--; $j--;
}
if (!$res && $i > 0 && file_exists(substr($tmp, 0, ($i + 1))."/main.inc.php")) {
	$res = @include substr($tmp, 0, ($i + 1))."/main.inc.php";
}
if (!$res && $i > 0 && file_exists(dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php")) {
	$res = @include dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php";
}
// Try main.inc.php using relative path
if (!$res && file_exists("../main.inc.php")) {
	$res = @include "../main.inc.php";
}
if (!$res && file_exists("../../main.inc.php")) {
	$res = @include "../../main.inc.php";
}
if (!$res && file_exists("../../../main.inc.php")) {
	$res = @include "../../../main.inc.php";
}
if (!$res) {
	die("Include of main fails");
}

require_once DOL_DOCUMENT_ROOT.'/core/class/html.formfile.class.php';

// Load translation files required by the page
$langs->loadLangs(array("gpeccustom@gpeccustom"));

$action = GETPOST('action', 'aZ09');
$contextpage = GETPOST('contextpage', 'aZ') ? GETPOST('contextpage', 'aZ') : 'userpositionlist'; // To manage different context of search
$sortfield = GETPOST('sortfield', 'aZ09comma');
$toselect   = GETPOST('toselect', 'array'); // Array of ids of elements selected into a list
$mode       = GETPOST('mode', 'aZ');
$sortorder = GETPOST('sortorder', 'aZ09comma');

$action     = GETPOST('action', 'aZ09') ?GETPOST('action', 'aZ09') : 'view'; // The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = GETPOST('massaction', 'alpha'); // The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files', 'int'); // Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha'); // Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha'); // We click on a Cancel button
$toselect   = GETPOST('toselect', 'array'); // Array of ids of elements selected into a list
$contextpage = GETPOST('contextpage', 'aZ') ? GETPOST('contextpage', 'aZ') : 'positionlist'; // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha'); // Go back to a dedicated page
$optioncss = GETPOST('optioncss', 'aZ'); // Option for the css output (always '' except when 'print')
$mode       = GETPOST('mode', 'aZ');

$id = GETPOST('id', 'int');
$ref = GETPOST('ref', 'alpha');

// Load variable for pagination
$limit = GETPOST('limit', 'int') ? GETPOST('limit', 'int') : $conf->liste_limit;
$sortfield = GETPOST('sortfield', 'aZ09comma');
$sortorder = GETPOST('sortorder', 'aZ09comma');
$max = 5;
$now = dol_now();

// Security check - Protection if external user
$socid = GETPOST('socid', 'int');
if (isset($user->socid) && $user->socid > 0) {
	$action = '';
	$socid = $user->socid;
}

// Security check (enable the most restrictive one)
//if ($user->socid > 0) accessforbidden();
//if ($user->socid > 0) $socid = $user->socid;
if (!isModEnabled('gpeccustom')) {
	accessforbidden('Module not enabled');
}

if (! $user->hasRight('gpeccustom', 'indicators', 'read')) {
	accessforbidden();
}
//restrictedArea($user, 'gpeccustom', 0, 'gpeccustom_myobject', 'myobject', '', 'rowid');
//if (empty($user->admin)) {
//	accessforbidden('Must be admin');
//}


/*
 * View
 */

$form = new Form($db);
$formfile = new FormFile($db);


llxHeader("", $langs->trans("Compétences et formations"));

print load_fiche_titre($langs->trans("Indicateurs des compétences et des formations"), '', 'fa-stream');

// print load_fiche_titre($langs->trans("Indicateurs des compétences"), '', 'fa-shapes');

 require_once DOL_DOCUMENT_ROOT.'/custom/gpeccustom/class/cvtec.class.php';
 require_once DOL_DOCUMENT_ROOT.'/custom/gpeccustom/class/job.class.php';
 require_once DOL_DOCUMENT_ROOT.'/custom/gpeccustom/class/position.class.php';
 
//  $arr_skill_jobs = GETPOST('arr_skill_jobs');
 $arr_users = GETPOST('arr_users'); 
 $filter_fk_user = GETPOST('filter_fk_user');
 $arr_jobs = GETPOST('arr_jobs');
 $job_fk_user = GETPOST('job_fk_user');
//  $arr_skill = GETPOST('arr_skill');
//  $skill_fk_user = GETPOST('skill_fk_user');
//  $nbusers_fk_user = GETPOST('nbusers_fk_user');
//  $arr_agence = GETPOST('arr_agence');
//  $skill_val_user = GETPOST('skill_val_user');
//  $arr_val_skill = GETPOST('arr_val_skill');
 ?>
 <style>

	 /* .dolgraphchart {
		width:-webkit-fill-available!important;
	 }
	 .dolgraphchart canvas {
    	width: calc(100% - 2px) !important;	
	}
	#placeholder_idgraphcvjob, #placeholder_idgraphcvskill, #placeholder_idgraphnbevaluated {
		/* width: auto!important; */
	/* }  */

	/* .fichecenter {
		display: flex;
		flex-wrap: wrap;
		justify-content: space-between;
	} */

	/* .fichethirdleft, .fichetwothirdright {
		box-sizing: border-box;
		margin-bottom: 20px;
	} */

	/* Responsive style  */
	.dolgraphchart {
		width: 100% !important;
		max-width: 100%; 
		height: auto; 
		box-sizing: border-box; 
	}

	.dolgraphchart canvas {
		width: 100% !important; 
		height: auto !important; 
		display: block; 
	}

	#placeholder_idgraphcvjob,
	#placeholder_idgraphcvskill,
	#placeholder_idgraphnbevaluated {
		width: auto !important; 
		height: auto !important; 
		margin: 0 auto; 
	}

	/* Media Queries pour une meilleure gestion sur petits écrans */
	@media (max-width: 768px) {
		.dolgraphchart {
			width: 95% !important; 
			margin: 0 auto; 
		}
		.dolgraphchart canvas {
			width: 100% !important;
		}
	}
	 
</style>
<?php
require_once DOL_DOCUMENT_ROOT.'/custom/gpeccustom/lib/gpeccustom_cvtec.lib.php';
$cv = new CVTec($db);
$head = gcfPrepareHead();
print dol_get_fiche_head($head, 'establishments', $langs->trans("HRM"), -1, "hrm", 0, '');
print '<br><br>';
// Statistics
//get file to require function displaying graphs
require_once DOL_DOCUMENT_ROOT.'/custom/gpeccustom/lib/graph_skill.php';

print '<div class="fichecenter"><div class="fichethirdleft">';
$tmp = getOpenJobsLineChart($cv);

if ($tmp) {
	print $tmp;
	print '<br>';
	print '<br>';
}
print '</div><div class="fichetwothirdright">';
$tmp = getOpenSkillsLineChart($cv);
if ($tmp) {
	print $tmp;
	print '<br>';
	print '<br>';
}
print '</div>';
print '</div><div class="fichecenter"><div class="fichethirdleft">';
$tmp = getAVGSkillsByJobsPolarChart($cv);

if ($tmp) {
	print $tmp;
	print '<br>';
}

print '</div><div class="fichetwothirdright">';
$tmp = getNBEvalSkillsBarChart($cv);
if ($tmp) {
	print $tmp;
	print '<br>';
}
print '</div>';
print '</div><div class="fichecenter">';
$tmp = getAVGSkillsPolarChart($cv);

if ($tmp) {
	print $tmp;
	print '<br>';
}
print '</div><div class="fichecenter">';
$tmp = getSkillsAlertBarChart($cv);

if ($tmp) {
	print $tmp;
	print '<br>';
}
print '</div>';

// include list to alert not evaluated and not affected salaries to jobs
// if($user->id == 412) {
	print '<div class="fichecenter">';
	include DOL_DOCUMENT_ROOT.'/custom/gpeccustom/users_not_valid_list.php';
	print '</div>';
// }

print '<div class="fichecenter"><div class="fichethirdleft" style="width: calc(60% - 14px);">';
include DOL_DOCUMENT_ROOT.'/custom/gpeccustom/users_not_eval_list.php';
print '</div><div class="fichetwothirdright" style="width: calc(40% - 14px)!important;">';
include DOL_DOCUMENT_ROOT.'/custom/gpeccustom/users_not_affected_list.php';
print '</div></div>';

// End of page
llxFooter();
$db->close();
